# Generated by Django 4.2.9 on 2024-02-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flujos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
    ]
